config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to '/new'
    else
      render :new
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>編集しましょう</h1>

<%= form_with(model: @todo) do |f| %>
    <div>
        <%= f.label :description, '中身' %><br>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.submit '更新する' %>
    </div>
<% end %>

<%= link_to '一覧に戻る', todos_path %>

app/views/todos/index.html.erb
<h1>Todoリスト</h1>

<ul>
    <% @todos.each do |todo| %>
        <li>
            <%= link_to(todo.title, todo_path(todo)) %>
        </li>
    <% end %>
</ul>

app/views/todos/new.html.erb
<h1>新しいTodoを作る</h1>

<%= form_with(model: @todo, url: '/todos', method: :post, local: true) do |f| %>
    <div>
        <%= f.label :title, "何をする？" %><br>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.submit "作成" %>
    </div>
<% end %>

app/views/todos/show.html.erb
<h1>Todo詳細</h1>

<div>
    <p><%= @todo.title %></p>
</div>

<div>
    <p><%= @todo.description %></p>
</div>

<div>
    <p><%= @todo.date %></p>
</div>

<%= link_to '編集', edit_todo_path(@todo) %>

<%= link_to '一覧に戻る', todos_path %>